#!/usr/bin/env python
# PREP_REPLAY_GAMES

import sys

import random_ai

########################################################################
# Initial setup
if len(sys.argv) < 2:
  raise ValueError("Usage: prep_replay_games <dirname>")

DIRNAME = sys.argv[1]

d = random_ai.PHPBMClientOutputWriter(DIRNAME)
for gamepath in d.find_games():
  sys.stderr.write("Prepping game for replay from: %s\n" % gamepath)
  d.translate_game(gamepath)
